### ISSUE TITLE
Does not work with .mcpacks that have extra subfolders in them.

### ISSUE THREAD

**Issue by NoFatAsiansPlz** [chegele/BDSAddonInstaller#1]
Failed to install an .mcpack until I removed the extra subfolders and rezipped the .mcpack and installed perfectly. Otherwise super great tool btw!

**Comment by chegele** [comment]
> Failed to install an .mcpack until I removed the extra subfolders and rezipped the .mcpack and installed perfectly. Otherwise super great tool btw!

Can you provide a link or upload the original pack?

**Comment by NoFatAsiansPlz** [comment]
https://mcpedl.com/esbe-2g/

Here's an example of one. Had to move all the files up just one folder.

**Comment by chegele** [comment]
This has been resolved in v1.0.4, thanks for reaching out. 

https://github.com/chegele/BDSAddonInstaller/commit/5f6569b4bb3b75eeaeeb3a3073cb6b5887e259dd
