### ISSUE TITLE
So i joined the discord for support and got immediately banned?

### ISSUE THREAD

**Issue by ghost** [chegele/BDSAddonInstaller#2]
I ran into a issue with the addon auto installer and joined the discord for some help and got banned for no reason.

**Comment by chegele** [comment]
> I ran into a issue with the addon auto installer and joined the discord for some help and got banned for no reason.

I removed you from the banned member list. You joined during a small raid attempt on our public servers. You are also welcome to reach out to me directly @ Chegs#6999
