### ISSUE TITLE
Error on install package .mcpack

### ISSUE THREAD

**Issue by enniosousa** [chegele/BDSAddonInstaller#3]
```shel
C:\Users\ennio\Documents\Minecraft Bedrock Server\bedrock-server-1.14.60.5>bds-addon-installer
internal/modules/cjs/loader.js:1149
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\ennio\AppData\Roaming\npm\node_modules\bds-addon-installer\cli.js
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1149:13)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:977:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:877:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m {
  code: [32m'ERR_REQUIRE_ESM'[39m
}
```

**Comment by chegele** [comment]
> ```
> C:\Users\ennio\Documents\Minecraft Bedrock Server\bedrock-server-1.14.60.5>bds-addon-installer
> internal/modules/cjs/loader.js:1149
>       throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
>       ^
> 
> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\ennio\AppData\Roaming\npm\node_modules\bds-addon-installer\cli.js
> �[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1149:13)�[39m
> �[90m    at Module.load (internal/modules/cjs/loader.js:977:32)�[39m
> �[90m    at Function.Module._load (internal/modules/cjs/loader.js:877:14)�[39m
> �[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)�[39m
> �[90m    at internal/main/run_main_module.js:18:47�[39m {
>   code: �[32m'ERR_REQUIRE_ESM'�[39m
> }
> ```

It seems to be having trouble loading the ESM module, which is only supported on newer versions of node.js. Can you run the below command to check your node version and let me know what the results are? 

```
node -v
```

**Comment by enniosousa** [comment]
```
C:\Users\ennio>node -v
v12.16.3
C:\Users\ennio>
```

**Comment by chegele** [comment]
> ```
> C:\Users\ennio>node -v
> v12.16.3
> C:\Users\ennio>
> ```

You need to be running at least version 14.1.0. You can get the update @ https://nodejs.org/dist/v14.3.0/node-v14.3.0-x64.msi

**Comment by enniosousa** [comment]
> You need to be running at least version 14.1.0. You can get the update @ https://nodejs.org/dist/v14.3.0/node-v14.3.0-x64.msi

thank you so much @chegele 

Please add the node version as dependency, so on installing the problem will be reported.

Now it worked perfectly. More one time thanks for you package

```
C:\Users\ennio>node -v
v14.3.0

C:\Users\ennio>cd C:\Users\ennio\Documents\Minecraft Bedrock Server\bedrock-server-1.14.60.5

C:\Users\ennio\Documents\Minecraft Bedrock Server\bedrock-server-1.14.60.5>bds-addon-installer

Running Bedrock Dedicated Server Addon Installer...
[28/05/2020 00:58:01] GENERAL BDSAddonInstaller - Installing TexturadoDeew...
[28/05/2020 00:58:01] GENERAL BDSAddonInstaller - Successfully installed the TexturadoDeew pack.

C:\Users\ennio\Documents\Minecraft Bedrock Server\bedrock-server-1.14.60.5>
```
